services:
  eureka-server:
    build:
      context: ./EurekaServer
    container_name: foodnutri-eureka-server
    ports:
      - "8761:8761"

  test-service:
    build:
      context: ./TestService
    container_name: foodnutri-test-service
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka/
      PROFILE_SERVICE_URL: http://profile-service:8082
    expose:
      - "8080"

  profile-service:
    build:
      context: ./ProfileService
    container_name: foodnutri-profile-service
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka/
    expose:
      - "8082"

  challenge-service:
    build:
      context: ./ChallengeService
    container_name: foodnutri-challenge-service
    depends_on:
      - eureka-server
      - test-service
    environment:
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka/
      FOOD_SERVICE_URL: http://test-service:8080
      PROFILE_SERVICE_URL: http://profile-service:8082
    expose:
      - "8081"

  api-gateway:
    build:
      context: ./ApiGateway
    container_name: foodnutri-api-gateway
    depends_on:
      - eureka-server
      - test-service
      - profile-service
      - challenge-service
    environment:
      EUREKA_CLIENT_SERVICE_URL: http://eureka-server:8761/eureka/
      GATEWAY_ALLOWED_ORIGINS: http://localhost:8085,http://localhost:5173,http://localhost:3000
    ports:
      - "8085:8085"
