spring:
  application:
    name: ChallengeService
  datasource:
    url: jdbc:h2:mem:challengedb
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:false}

server:
  port: 8081

food:
  service:
    url: ${FOOD_SERVICE_URL:http://localhost:8080}

profile:
  service:
    url: ${PROFILE_SERVICE_URL:http://localhost:8082}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
